# Generated by Django 4.1.7 on 2023-05-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_protocol_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='tracker.exercise'),
        ),
    ]
