# Generated by Django 4.1.7 on 2023-05-28 02:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0004_entry_delete_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Entries',
        ),
    ]
