# Generated by Django 4.1.7 on 2023-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'regular'), (2, 'student'), (3, 'coach')], default=1),
        ),
    ]
